version: "3.8"

services:
  pg_1:
    build:
    context: .
    dockerfile: Dockerfile
    container_name: PG_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pg_primary_data:/var/lib/postgresql/data
      - ./primary/init:/docker-entrypoint-initdb.d
    networks:
      - pg_network

  pg_2:
    image: postgres:16
    container_name: PG_2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5434:5432"
    command: ["postgres", "-D", "/var/lib/postgresql/data"]
    volumes:
      - pg_replica_data:/var/lib/postgresql/data
      - ./replica/init:/docker-entrypoint-initdb.d
    networks:
      - pg_network

  pgbench:
    image: postgres:16
    container_name: PGBENCH
    entrypoint: ["/bin/bash"]
    tty: true
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  pg_primary_data:
  pg_replica_data:

